### ISSUE TITLE
[Bug] Gene sources don't show on Servers

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#35]
**Describe the bug**

**To Reproduce**
1. In SP, check recipes for a DNA Helix
2. Look at DNA Decryptor
3. See the source mob listed on the left
4. In MP, do the same
5. No sources shown for any gene

**Expected behavior**
Gene sources should be shown

**Screenshots**
These are all missing on servers. visible in SP only
![image](https://github.com/user-attachments/assets/46b5d980-f856-4f12-94db-b58a70fcf7a6)

**Additional context**
![image](https://github.com/user-attachments/assets/f14bb308-0aef-4ac4-8bbe-f21e455d7b3d)

**Comment by DoomSquirter** [comment]
so, a followup to this

I was absolutely having this issue earlier

I am pretty sure I restarted pack many hours ago and now I see the tab I should see

(on server)

not sure what triggered this or fixed it

servermate confirmed they see it too now

edit:
so...  correction
some genes I can see 2 pages when I click on the helix
some genes I only get 1 page which is the description one
there's no rhyme or reason it seems as to what differentiates the two

**Comment by aaronhowser1** [comment]
```
[20:54:32] [Render thread/ERROR] [EMI/]: [EMI] Exception serializing stack geneticsresequenced:dna_helix{geneticsresequenced:gene=>GeneItemComponent(geneHolder=Reference{ResourceKey[geneticsresequenced:gene / geneticsresequenced:dragons_breath]=Gene(dnaPointsRequired=20, allowedEntities=DirectSet[[Reference{ResourceKey[minecraft:entity_type / minecraft:player]=entity.minecraft.player}]], potionDetails=Optional.empty, attributeModifiers=[], scaresEntitiesWithTag=Optional.empty)})} x1
java.lang.IllegalStateException: Element Reference{ResourceKey[geneticsresequenced:gene / geneticsresequenced:dragons_breath]=Gene(dnaPointsRequired=20, allowedEntities=DirectSet[[Reference{ResourceKey[minecraft:entity_type / minecraft:player]=entity.minecraft.player}]], potionDetails=Optional.empty, attributeModifiers=[], scaresEntitiesWithTag=Optional.empty)} is not valid in current registry set
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.api.stack.serializer.EmiStackSerializer.serialize(EmiStackSerializer.java:82)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.api.stack.serializer.EmiStackSerializer.serialize(EmiStackSerializer.java:21)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.registry.EmiIngredientSerializers.serialize(EmiIngredientSerializers.java:32)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.getSerialized(EmiIngredientSerializer.java:19)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.runtime.EmiSidebars.save(EmiSidebars.java:72)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.runtime.EmiPersistentData.save(EmiPersistentData.java:21)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.runtime.EmiSidebars.lookup(EmiSidebars.java:47)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.api.EmiApi.setPages(EmiApi.java:241)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.api.EmiApi.displayRecipes(EmiApi.java:142)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.screen.EmiScreenManager.stackInteraction(EmiScreenManager.java:1163)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.screen.EmiScreenManager.keyPressed(EmiScreenManager.java:1067)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.handler$zzg000$emi$onKey(KeyboardHandler.java:642)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.keyPress(KeyboardHandler.java:407)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.lambda$setup$8(KeyboardHandler.java:515)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:98)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.lambda$setup$9(KeyboardHandler.java:515)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at MC-BOOTSTRAP/org.lwjgl@3.3.3+5/org.lwjgl.system.JNI.invokeV(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:134)
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:143)
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.Window.updateDisplay(Window.java:294)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1223)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:813)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.NeoForgeClientUserdevLaunchHandler.runService(NeoForgeClientUserdevLaunchHandler.java:23)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at DevLaunch@1.0.1/net.neoforged.devlaunch.Main.main(Main.java:55)
```

Well that's odd...

**Comment by aaronhowser1** [comment]
Trying to spawn in items from EMI on a server crashes for me. I assume this is some like, client/server datapack desync thing going on

**Comment by aaronhowser1** [comment]
This is a surprisingly difficult problem to track down

**Comment by aaronhowser1** [comment]
emilyploszaj/emi/issues/774

**Comment by aaronhowser1** [comment]
That EMI issue was closed so hopefully this should be fixed
